Update newrepolist.yaml

diff --git a/.github/workflows/newrepolist.yaml b/.github/workflows/newrepolist.yaml
--- a/.github/workflows/newrepolist.yaml
+++ b/.github/workflows/newrepolist.yaml
@@ -70,6 +70,11 @@ jobs:
           name: error_log
           path: error.log
 
+      - name: Apply Branch Protection to non compliant repos
+        id: apply_BP_script
+        run: |
+          python applybranchprotection.py -pat ${{ secrets.MY_PAT }} -org my-practiceorg || (echo "An error occurred while running the script." > error.log && exit 1)
+
       - name: Notify Slack with CSV Link
         if: success()
         run: |
@@ -80,7 +85,4 @@ jobs:
         run: |
           curl -X POST -H 'Content-type: application/json' --data '{"text":"There was an error running the GitHub Repos script. You can download the error log here: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
 
-      - name: Run GitHub Repos Script
-        id: apply_BP_script
-        run: |
-          python applybranchprotection.py -pat ${{ secrets.MY_PAT }} -org my-practiceorg || (echo "An error occurred while running the script." > error.log && exit 1)
+      
